name: CI/CD for Spring Boot with GHCR

on:
  push:
    branches:
      - master  # Jalanin pas ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java & Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Build JAR pake Maven
      - name: Build JAR
        run: mvn clean package -DskipTests

      # Step 4: Login ke GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Build Docker Image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

      # Step 6: Push ke GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/my-app:latest

      # (Opsional) Step 7: Deploy ke server (misalnya VPS)
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.5.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8080:8080 ghcr.io/${{ github.repository }}/my-app:latest
