name: CI/CD for Spring Boot with GHCR (GraalVM Native)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up  JDK
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build JAR 
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4: Set up Container Buildx
      - name: Set up Container Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Login ke GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 6: Build dan Push Docker Image ke GHCR
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: ${{ secrets.IMAGE_NAME }}
          push: ${{ github.ref_name == 'master' }}
          cache-from: type=registry,ref=${{ secrets.IMAGE_NAME }}

      # Step 7: Deploy ke server via SSH
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker images | grep '${{ secrets.IMAGE_NAME }}' | grep '<none>' | awk '{print $3}' | xargs --no-run-if-empty docker rmi
