name: CI/CD for Spring Boot with GHCR (GraalVM Native)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up GraalVM JDK
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: 23
          distribution: graalvm
          components: native-image
          java-package: jdk
          check-latest: true
          server-id : github
          server-username : ${{ github.actor }}
          server-password : ${{ secrets.GHCR_TOKEN }}
          native-image-job-reports: 'true'

      # Step 4: Build Native Image
      - name: Build Native Image Using Maven
        run: mvn -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          path: target/actions-demo

      - name: Set up Container Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Login ke GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 6: Build Docker Image (Multistage)
      - name: Build Docker image
        run: docker build . -t ghcr.io/crobin1011/bcc-intern/ignit:latest

      # Step 7: Push ke GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/crobin1011/bcc-intern/ignit:latest

      # Step 8: Deploy ke server 
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/ignit:latest
            docker-compose down
            docker-compose up -d --build
