name: CI/CD for Spring Boot with GHCR

on:
  push:
    branches:
      - master  # Jalanin pas ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java & Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Login ke GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}/ignit:latest 

      # Step 5: Push ke GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/ignit:latest

      # Step 6: Deploy ke server 
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.5.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/ignit:latest
            docker-compose down
            docker-compose up -d --build
